services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: home-service
    volumes:
      - postgres:/data/postgres
      - ./home-service.sql:/docker-entrypoint-initdb.d/home-service.sql
    ports:
      - '5432:5432'

  backend-service:
    container_name: home-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  backend:
    driver: bridge

volumes:
  postgres:
