spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/home-service}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
    properties.hibernate.cache.use_second_level_cache: false

  # Redis spring.data.redis.host
  data:
    redis:
      host: localhost
      port: 6379

  #Sendgrid
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    fromEmail: ${SENDGRID_FROM_EMAIL}
    templateId: ${SENDGRID_TEMPLATE_ID}
    templateIdChangePassword: ${SENDGRID_TEMPLATE_ID_CHANGE_PASSWORD}
    verificationLink: http://localhost:8080/register/confirm-email
    changePasswordLink: http://localhost:8080/auth/reset-password

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:8080
    title: Backend service
    version: 1.0.0

jwt:
  access-key: ${JWT_ACCESS_KEY}
  expiration: ${JWT_EXPIRATION}
  refresh-token: ${JWT_REFRESH_KEY}
  reset-key: ${JWT_RESET_KEY}

app:
  notification:
    search-radius-meters: 5000
    max-taskers: 10
  