spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/home-service}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
    properties.hibernate.cache.use_second_level_cache: false

  # Redis spring.data.redis.host
  data:
    redis:
      host: localhost
      port: 6379

  #Sendgrid
  sendgrid:
    api-key: ${SENDGRID_API_KEY:SENDGRID_API_KEY}
    fromEmail: ${SENDGRID_FROM_EMAIL:SENDGRID_FROM_EMAIL}
    templateId: ${SENDGRID_TEMPLATE_ID:SENDGRID_TEMPLATE_ID}
    templateIdChangePassword: ${SENDGRID_TEMPLATE_ID_CHANGE_PASSWORD:SENDGRID_TEMPLATE_ID_CHANGE_PASSWORD}
    verificationLink: https://b639-14-191-193-79.ngrok-free.app/register/confirm-email
    changePasswordLink: https://6d13-14-191-193-7.ngrok-free.app/auth/reset-password

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:8080
    title: Backend service
    version: 1.0.0

jwt:
  access-key: ${JWT_ACCESS_KEY:JWT_ACCESS_KEY}
  expiration: ${JWT_EXPIRATION:10}
  refresh-token: ${JWT_REFRESH_KEY:JWT_REFRESH_KEY}
  reset-key: ${JWT_RESET_KEY:JWT_RESET_KEY}

app:
  notification:
    search-radius-meters: 5000
    max-taskers: 10

vnpay:
  version: ${VNP_VERSION:VNP_VERSION}
  tmn_Code: ${VNP_TMNCODE:VNP_TMNCODE}
  hash_secret: ${VNP_HASH_SECRET:VNP_HASH_SECRET}
  payment_url: ${VNP_PAYMENT_URL:VNP_PAYMENT_URL}
  return_url: ${VNP_RETURN_URL:VNP_RETURN_URL}

cloudinary:
  cloud_name: ${CLOUDINARY_NAME:CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_API_KEY:CLOUDINARY_API_KEY}
  api_secret: "CLOUDINARY_API_SECRET:CLOUDINARY_API_SECRET"
  